# Site settings
author: Christopher Dutcher
title: Why I decided to study Software Engineering
header-img: img/home-bg.png
email: cadutcher@icloud.com
copyright_name: Christopher Dutcher
description: > # this means to ignore newlines until "baseurl:"
  First mile blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dutchmile

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
